version: "3.8"

services:
  sekolah-docker:
    container_name: sekolah_kurikulum_docker
    image: sekolah_kurikulum_image:latest
    ports:
      - "8080:8080"
    environment:
      - HOME=${HOME}
    volumes:
      - /home/erickhene/logs/docker/sekolah:/home/erickhene/logs/local/sekolah